<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class FleetSeeder extends Seeder
{
    public function run()
    {
        $now = date('Y-m-d H:i:s');

        // 1. Users
        $users = [
            [
                'name'       => 'Chief Fleet Admin',
                'email'      => 'admin@fleet.com',
                'password'   => password_hash('admin123', PASSWORD_DEFAULT),
                'role'       => 'admin',
                'phone'      => '+63 917 555 0100',
                'status'     => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name'       => 'Lead Dispatcher',
                'email'      => 'dispatcher@fleet.com',
                'password'   => password_hash('dispatch123', PASSWORD_DEFAULT),
                'role'       => 'dispatcher',
                'phone'      => '+63 918 555 0200',
                'status'     => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name'       => 'Safety & Maintenance Lead',
                'email'      => 'maintenance@fleet.com',
                'password'   => password_hash('maint123', PASSWORD_DEFAULT),
                'role'       => 'maintenance',
                'phone'      => '+63 919 555 0300',
                'status'     => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];
        $this->db->table('users')->insertBatch($users);

        // 2. Drivers
        $drivers = [
            [
                'driver_code'       => 'DRV-101',
                'first_name'        => 'Rodrigo',
                'last_name'         => 'Santos',
                'email'             => 'rodrigo.santos@fleet.com',
                'phone'             => '+63 917 111 2233',
                'license_number'    => 'N01-19-082914',
                'license_type'      => 'Professional Driver (Heavy Articulated)',
                'license_expiry'    => date('Y-m-d', strtotime('+2 years')),
                'status'            => 'on_trip',
                'safety_score'      => 98.50,
                'total_trips'       => 142,
                'address'           => '12 Sampaguita St, Pasig City',
                'emergency_contact' => 'Elena Santos (+63 917 888 1234)',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'driver_code'       => 'DRV-102',
                'first_name'        => 'Eduardo',
                'last_name'         => 'Reyes',
                'email'             => 'eduardo.reyes@fleet.com',
                'phone'             => '+63 918 222 3344',
                'license_number'    => 'N02-20-044812',
                'license_type'      => 'Professional Driver (Heavy Articulated)',
                'license_expiry'    => date('Y-m-d', strtotime('+1 year')),
                'status'            => 'on_trip',
                'safety_score'      => 96.00,
                'total_trips'       => 118,
                'address'           => '45 Dahlia Rd, Quezon City',
                'emergency_contact' => 'Maria Reyes (+63 918 999 5678)',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'driver_code'       => 'DRV-103',
                'first_name'        => 'Carlos',
                'last_name'         => 'Mendoza',
                'email'             => 'carlos.mendoza@fleet.com',
                'phone'             => '+63 919 333 4455',
                'license_number'    => 'N03-21-099231',
                'license_type'      => 'Professional Driver (Light & Medium)',
                'license_expiry'    => date('Y-m-d', strtotime('+3 years')),
                'status'            => 'available',
                'safety_score'      => 99.20,
                'total_trips'       => 87,
                'address'           => '88 Acacia Blvd, Mandaluyong City',
                'emergency_contact' => 'Lourdes Mendoza (+63 919 111 9876)',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'driver_code'       => 'DRV-104',
                'first_name'        => 'Mark',
                'last_name'         => 'Villanueva',
                'email'             => 'mark.villanueva@fleet.com',
                'phone'             => '+63 920 444 5566',
                'license_number'    => 'N04-18-011243',
                'license_type'      => 'Professional Driver (Commercial Van)',
                'license_expiry'    => date('Y-m-d', strtotime('+18 months')),
                'status'            => 'available',
                'safety_score'      => 94.00,
                'total_trips'       => 165,
                'address'           => '23 Malakas St, Makati City',
                'emergency_contact' => 'Joy Villanueva (+63 920 222 3456)',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'driver_code'       => 'DRV-105',
                'first_name'        => 'Arnel',
                'last_name'         => 'Bautista',
                'email'             => 'arnel.bautista@fleet.com',
                'phone'             => '+63 921 555 6677',
                'license_number'    => 'N05-22-076123',
                'license_type'      => 'Professional Driver (Heavy Articulated)',
                'license_expiry'    => date('Y-m-d', strtotime('+6 months')),
                'status'            => 'off_duty',
                'safety_score'      => 97.80,
                'total_trips'       => 53,
                'address'           => '101 Bayani Ave, Taguig City',
                'emergency_contact' => 'Grace Bautista (+63 921 333 7890)',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
        ];
        $this->db->table('drivers')->insertBatch($drivers);

        // 3. Vehicles
        $vehicles = [
            [
                'vehicle_code'        => 'FLT-01',
                'plate_number'        => 'NAA-8120',
                'vin'                 => '1HTMMAAL4KH123401',
                'make'                => 'Freightliner',
                'model'               => 'Cascadia 126',
                'year'                => 2023,
                'type'                => 'semi_truck',
                'fuel_type'           => 'diesel',
                'max_payload_kg'      => 24000.00,
                'fuel_capacity_liters'=> 450.00,
                'odometer_km'         => 64320.50,
                'current_latitude'    => 14.583333, // Manila Port
                'current_longitude'   => 120.966667,
                'current_speed'       => 58.40,
                'current_fuel_level'  => 82.50,
                'engine_status'       => 'running',
                'status'              => 'in_transit',
                'current_driver_id'   => 1,
                'last_service_date'   => date('Y-m-d', strtotime('-45 days')),
                'next_service_km'     => 70000.00,
                'created_at'          => $now,
                'updated_at'          => $now,
            ],
            [
                'vehicle_code'        => 'FLT-02',
                'plate_number'        => 'NCB-4519',
                'vin'                 => '4V4NC9EH1MN234502',
                'make'                => 'Volvo',
                'model'               => 'VNL 860',
                'year'                => 2024,
                'type'                => 'semi_truck',
                'fuel_type'           => 'diesel',
                'max_payload_kg'      => 26000.00,
                'fuel_capacity_liters'=> 500.00,
                'odometer_km'         => 32180.20,
                'current_latitude'    => 14.282900, // Laguna Technopark
                'current_longitude'   => 121.077200,
                'current_speed'       => 64.20,
                'current_fuel_level'  => 68.00,
                'engine_status'       => 'running',
                'status'              => 'in_transit',
                'current_driver_id'   => 2,
                'last_service_date'   => date('Y-m-d', strtotime('-20 days')),
                'next_service_km'     => 40000.00,
                'created_at'          => $now,
                'updated_at'          => $now,
            ],
            [
                'vehicle_code'        => 'FLT-03',
                'plate_number'        => 'NFE-3392',
                'vin'                 => '1FTNE3Y82PKA34503',
                'make'                => 'Ford',
                'model'               => 'Transit 350 High Roof',
                'year'                => 2023,
                'type'                => 'delivery_van',
                'fuel_type'           => 'diesel',
                'max_payload_kg'      => 2100.00,
                'fuel_capacity_liters'=> 95.00,
                'odometer_km'         => 41500.00,
                'current_latitude'    => 14.576400, // Pasig Hub
                'current_longitude'   => 121.085100,
                'current_speed'       => 0.00,
                'current_fuel_level'  => 92.00,
                'engine_status'       => 'off',
                'status'              => 'active',
                'current_driver_id'   => null,
                'last_service_date'   => date('Y-m-d', strtotime('-15 days')),
                'next_service_km'     => 45000.00,
                'created_at'          => $now,
                'updated_at'          => $now,
            ],
            [
                'vehicle_code'        => 'FLT-04',
                'plate_number'        => 'NKG-9014',
                'vin'                 => 'JALC4B165R7456704',
                'make'                => 'Isuzu',
                'model'               => 'NPR-HD 16ft Box',
                'year'                => 2022,
                'type'                => 'box_truck',
                'fuel_type'           => 'diesel',
                'max_payload_kg'      => 5500.00,
                'fuel_capacity_liters'=> 140.00,
                'odometer_km'         => 89230.10,
                'current_latitude'    => 14.676000, // Quezon City Service Center
                'current_longitude'   => 121.043700,
                'current_speed'       => 0.00,
                'current_fuel_level'  => 45.00,
                'engine_status'       => 'off',
                'status'              => 'maintenance',
                'current_driver_id'   => null,
                'last_service_date'   => date('Y-m-d', strtotime('-120 days')),
                'next_service_km'     => 90000.00,
                'created_at'          => $now,
                'updated_at'          => $now,
            ],
            [
                'vehicle_code'        => 'FLT-05',
                'plate_number'        => 'NPH-7621',
                'vin'                 => 'WD3PE8CD8NP567805',
                'make'                => 'Mercedes-Benz',
                'model'               => 'Sprinter 2500 Cargo',
                'year'                => 2024,
                'type'                => 'delivery_van',
                'fuel_type'           => 'diesel',
                'max_payload_kg'      => 1950.00,
                'fuel_capacity_liters'=> 90.00,
                'odometer_km'         => 18450.80,
                'current_latitude'    => 14.425300, // Alabang
                'current_longitude'   => 121.041600,
                'current_speed'       => 22.10,
                'current_fuel_level'  => 77.40,
                'engine_status'       => 'running',
                'status'              => 'active',
                'current_driver_id'   => 4,
                'last_service_date'   => date('Y-m-d', strtotime('-30 days')),
                'next_service_km'     => 25000.00,
                'created_at'          => $now,
                'updated_at'          => $now,
            ],
        ];
        $this->db->table('vehicles')->insertBatch($vehicles);

        // 4. Trips
        $trips = [
            [
                'trip_number'         => 'TRP-2026-001',
                'vehicle_id'          => 1,
                'driver_id'           => 1,
                'origin_address'      => 'Manila North Harbor, Port Area, Manila',
                'origin_lat'          => 14.583333,
                'origin_lng'          => 120.966667,
                'destination_address' => 'Clark Global City Distribution Hub, Pampanga',
                'destination_lat'     => 15.185500,
                'destination_lng'     => 120.540600,
                'cargo_type'          => 'Import Electronics & Microchips',
                'cargo_weight_kg'     => 18500.00,
                'distance_km'         => 98.40,
                'scheduled_departure' => date('Y-m-d 06:00:00'),
                'scheduled_arrival'   => date('Y-m-d 11:30:00'),
                'actual_departure'    => date('Y-m-d 06:20:00'),
                'actual_arrival'      => null,
                'start_odometer'      => 64220.00,
                'end_odometer'        => null,
                'status'              => 'in_transit',
                'priority'            => 'urgent',
                'notes'               => 'High-value cargo with seal verification required at checkpoint.',
                'created_by'          => 2,
                'created_at'          => $now,
                'updated_at'          => $now,
            ],
            [
                'trip_number'         => 'TRP-2026-002',
                'vehicle_id'          => 2,
                'driver_id'           => 2,
                'origin_address'      => 'Laguna Technopark Special Economic Zone, Biñan',
                'origin_lat'          => 14.282900,
                'origin_lng'          => 121.077200,
                'destination_address' => 'Batangas International Container Port',
                'destination_lat'     => 13.756500,
                'destination_lng'     => 121.058300,
                'cargo_type'          => 'Automotive Parts for Export',
                'cargo_weight_kg'     => 22400.00,
                'distance_km'         => 72.80,
                'scheduled_departure' => date('Y-m-d 07:30:00'),
                'scheduled_arrival'   => date('Y-m-d 12:00:00'),
                'actual_departure'    => date('Y-m-d 07:45:00'),
                'actual_arrival'      => null,
                'start_odometer'      => 32110.00,
                'end_odometer'        => null,
                'status'              => 'in_transit',
                'priority'            => 'normal',
                'notes'               => 'Export vessel loading cut-off at 15:00.',
                'created_by'          => 2,
                'created_at'          => $now,
                'updated_at'          => $now,
            ],
            [
                'trip_number'         => 'TRP-2026-003',
                'vehicle_id'          => 3,
                'driver_id'           => 3,
                'origin_address'      => 'Pasig Logistics Depot, Pasig City',
                'origin_lat'          => 14.576400,
                'origin_lng'          => 121.085100,
                'destination_address' => 'BGC Retail Commercial Hub, Taguig',
                'destination_lat'     => 14.549200,
                'destination_lng'     => 121.050600,
                'cargo_type'          => 'Retail Apparel & Department Store Goods',
                'cargo_weight_kg'     => 1200.00,
                'distance_km'         => 18.50,
                'scheduled_departure' => date('Y-m-d 14:00:00'),
                'scheduled_arrival'   => date('Y-m-d 16:00:00'),
                'actual_departure'    => null,
                'actual_arrival'      => null,
                'start_odometer'      => 41500.00,
                'end_odometer'        => null,
                'status'              => 'scheduled',
                'priority'            => 'normal',
                'notes'               => 'Mall delivery window strictly between 15:00-18:00.',
                'created_by'          => 2,
                'created_at'          => $now,
                'updated_at'          => $now,
            ],
            [
                'trip_number'         => 'TRP-2026-004',
                'vehicle_id'          => 5,
                'driver_id'           => 4,
                'origin_address'      => 'Alabang Mega Warehouse, Muntinlupa',
                'origin_lat'          => 14.425300,
                'origin_lng'          => 121.041600,
                'destination_address' => 'Makati Central Business District, Makati',
                'destination_lat'     => 14.554700,
                'destination_lng'     => 121.024400,
                'cargo_type'          => 'Pharmaceutical Supplies & Vaccines (Cold Chain)',
                'cargo_weight_kg'     => 850.00,
                'distance_km'         => 24.20,
                'scheduled_departure' => date('Y-m-d 05:00:00', strtotime('-1 day')),
                'scheduled_arrival'   => date('Y-m-d 07:30:00', strtotime('-1 day')),
                'actual_departure'    => date('Y-m-d 05:05:00', strtotime('-1 day')),
                'actual_arrival'      => date('Y-m-d 07:15:00', strtotime('-1 day')),
                'start_odometer'      => 18426.60,
                'end_odometer'        => 18450.80,
                'status'              => 'completed',
                'priority'            => 'critical',
                'notes'               => 'Temperature monitored throughout transit. Successfully delivered on time.',
                'created_by'          => 1,
                'created_at'          => date('Y-m-d H:i:s', strtotime('-1 day')),
                'updated_at'          => date('Y-m-d H:i:s', strtotime('-1 day')),
            ],
        ];
        $this->db->table('trips')->insertBatch($trips);

        // 5. Telemetry Logs (Simulated breadcrumbs for vehicles)
        $telemetry = [
            [
                'vehicle_id'     => 1,
                'trip_id'        => 1,
                'latitude'       => 14.583333,
                'longitude'      => 120.966667,
                'speed_kmh'      => 58.40,
                'heading'        => 355.00,
                'fuel_level'     => 82.50,
                'engine_status'  => 'running',
                'battery_voltage'=> 14.1,
                'engine_temp_c'  => 88.5,
                'created_at'     => date('Y-m-d H:i:s', strtotime('-10 minutes')),
            ],
            [
                'vehicle_id'     => 2,
                'trip_id'        => 2,
                'latitude'       => 14.282900,
                'longitude'      => 121.077200,
                'speed_kmh'      => 64.20,
                'heading'        => 175.00,
                'fuel_level'     => 68.00,
                'engine_status'  => 'running',
                'battery_voltage'=> 14.2,
                'engine_temp_c'  => 91.0,
                'created_at'     => date('Y-m-d H:i:s', strtotime('-5 minutes')),
            ],
            [
                'vehicle_id'     => 5,
                'trip_id'        => null,
                'latitude'       => 14.425300,
                'longitude'      => 121.041600,
                'speed_kmh'      => 22.10,
                'heading'        => 20.00,
                'fuel_level'     => 77.40,
                'engine_status'  => 'running',
                'battery_voltage'=> 13.9,
                'engine_temp_c'  => 84.0,
                'created_at'     => date('Y-m-d H:i:s', strtotime('-2 minutes')),
            ],
        ];
        $this->db->table('telemetry_logs')->insertBatch($telemetry);

        // 6. Maintenance Records
        $maintenance = [
            [
                'reference_no'        => 'WO-2026-001',
                'vehicle_id'          => 4,
                'service_type'        => 'Heavy Duty Brake Pad Replacement & Rotor Surfacing',
                'priority'            => 'high',
                'scheduled_date'      => date('Y-m-d'),
                'completion_date'     => null,
                'odometer_at_service' => 89230.10,
                'service_center'      => 'Isuzu Fleet Service Hub - QC North',
                'technician_name'     => 'Danilo Ramos',
                'cost'                => 18500.00,
                'status'              => 'in_progress',
                'description'         => 'Front and rear brake pads reached 15% remaining life. Full replacement authorized.',
                'notes'               => 'Parts received and technician currently disassembling rear calipers.',
                'created_at'          => $now,
                'updated_at'          => $now,
            ],
            [
                'reference_no'        => 'WO-2026-002',
                'vehicle_id'          => 1,
                'service_type'        => 'Preventative 60,000 km Major Engine & Transmission Service',
                'priority'            => 'medium',
                'scheduled_date'      => date('Y-m-d', strtotime('-45 days')),
                'completion_date'     => date('Y-m-d', strtotime('-44 days')),
                'odometer_at_service' => 60120.00,
                'service_center'      => 'Freightliner Authorized Service Center',
                'technician_name'     => 'Victoriano Gomez',
                'cost'                => 34200.00,
                'status'              => 'completed',
                'description'         => 'Full synthetic oil change, fuel filters, air filter, and coolant flush.',
                'notes'               => 'Passed 50-point diagnostic check with zero fault codes.',
                'created_at'          => date('Y-m-d H:i:s', strtotime('-45 days')),
                'updated_at'          => date('Y-m-d H:i:s', strtotime('-44 days')),
            ],
            [
                'reference_no'        => 'WO-2026-003',
                'vehicle_id'          => 3,
                'service_type'        => '45,000 km Scheduled Service & Tire Rotation',
                'priority'            => 'low',
                'scheduled_date'      => date('Y-m-d', strtotime('+10 days')),
                'completion_date'     => null,
                'odometer_at_service' => 41500.00,
                'service_center'      => 'Ford Commercial Fleet Care',
                'technician_name'     => 'TBD',
                'cost'                => 12000.00,
                'status'              => 'scheduled',
                'description'         => 'Standard preventive maintenance and alignment check.',
                'notes'               => 'Slot booked for next Wednesday morning.',
                'created_at'          => $now,
                'updated_at'          => $now,
            ],
        ];
        $this->db->table('maintenance_records')->insertBatch($maintenance);

        // 7. Fuel Logs
        $fuelLogs = [
            [
                'receipt_no'      => 'PET-98124',
                'vehicle_id'      => 1,
                'driver_id'       => 1,
                'fuel_date'       => date('Y-m-d', strtotime('-1 day')),
                'odometer_km'     => 63890.00,
                'liters'          => 280.50,
                'cost_per_liter'  => 62.40,
                'total_cost'      => 17503.20,
                'fuel_station'    => 'Petron North Luzon Expressway Mega Station',
                'notes'           => 'Full tank before departure.',
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
            [
                'receipt_no'      => 'SHL-44129',
                'vehicle_id'      => 2,
                'driver_id'       => 2,
                'fuel_date'       => date('Y-m-d', strtotime('-2 days')),
                'odometer_km'     => 31750.00,
                'liters'          => 310.00,
                'cost_per_liter'  => 63.10,
                'total_cost'      => 19561.00,
                'fuel_station'    => 'Shell SLEX Southbound Mamplasan',
                'notes'           => 'Fleet card transaction.',
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
            [
                'receipt_no'      => 'CAL-77182',
                'vehicle_id'      => 3,
                'driver_id'       => 3,
                'fuel_date'       => date('Y-m-d', strtotime('-3 days')),
                'odometer_km'     => 41200.00,
                'liters'          => 65.00,
                'cost_per_liter'  => 62.80,
                'total_cost'      => 4082.00,
                'fuel_station'    => 'Caltex C5 E. Rodriguez Jr. Ave',
                'notes'           => 'Routine weekly top up.',
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
        ];
        $this->db->table('fuel_logs')->insertBatch($fuelLogs);

        // 8. Incidents
        $incidents = [
            [
                'incident_no'     => 'INC-2026-001',
                'vehicle_id'      => 4,
                'driver_id'       => 1,
                'trip_id'         => null,
                'incident_date'   => date('Y-m-d 14:35:00', strtotime('-5 days')),
                'severity'        => 'minor',
                'type'            => 'Tire Puncture / Slow Leak',
                'location'        => 'EDSA Guadalupe Northbound',
                'description'     => 'Driver noted low tire pressure warning on dashboard. Safely pulled over to emergency bay and utilized onboard inflator until service vehicle arrived.',
                'damage_estimate' => 2500.00,
                'status'          => 'resolved',
                'created_at'      => $now,
                'updated_at'      => $now,
            ],
        ];
        $this->db->table('incidents')->insertBatch($incidents);
    }
}
